### ISSUE TITLE
Conflict with PowerToys remapping keys

### ISSUE THREAD

**Issue by pearce89** [damienleroy/PowerAccent#3] opened 2022-04-27 10:48 UTC
Hello @damienleroy 👋 Thanks a lot for your amazing tool! 🙏

I noticed one small issue which I'm not sure if it will be possible to resolve: when PowerAccent is used together with PowerToys which has some keys remapping configuration in place, remapping is not working. In my case I have alt mapped to control and control to alt in PowerToys and together with PowerAccent it's not working. I also tried another tool called [holdkey.eu](https://holdkey.eu/) and it also breaks remapping in PowerToys. So I'm not sure if it's possible to solve.

Thank you again!

**Comment by damienleroy** [comment] 2022-05-03 21:50
Hello @pearce89 👋
Thank you for your feedback.
Unfortunaly I can't reproduce this issue on my side :(
I'm sure I missed something. But what I can see, there is some trouble remapping these keys when use with specific behavior (For example: https://github.com/microsoft/PowerToys/issues/3703).
Remapping them seems a bit tricky...

The PowerAccent tool don't use at any case the key `alt` or `ctrl`. So it should not have any incidence on it. It's why I'm not sure this issue can be resolving PowerAccent side.
Sorry. but be sure I will keep an eye on it 👀

**Closed** 2022-05-08 22:37 UTC

**Comment by damienleroy** [comment] 2022-09-02 15:45
Hi @sergey-pt 
In case of, I made some changes in the source code, which fix an issue I had with PowerToys (when I using Alt+arrow in an application). So I thought it may work for you also. You can try the last version if you want which include the fix:
https://github.com/damienleroy/PowerAccent/releases/tag/1.2.3

Also, be know PowerToys will include PowerAccent (called QuickAccent in PowerToys).

**Comment by sergey-pt** [comment] 2022-10-16 21:58
Thank you so much for the information @damienleroy ! 🙏
